let players = [
    { name: "Magnus Carlsen", 
    id: 1, 
    classicalRating: "2859", 
    rapidRating: "2834", 
    blitzRating: "2830", 
    games: [{ date: "2022-11-01", 
    white: "Magnus Carlsen", 
    black: "Ding Liren", 
    winner: "-1", 
    brilliantW: "0", 
    greatW: "0", 
    bestW: "0", 
    excellentW: "0", 
    goodW: "0", 
    bookW: "0", 
    inaccuracyW: "0", 
    mistakeW: "0", 
    blunderW: "0", 
    missedW: "0", 
    brilliantB: "0", 
    greatB: "0", 
    bestB: "0", 
    excellentB: "0", 
    goodB: "0", 
    bookB: "0", 
    inaccuracyB: "0", 
    mistakeB: "0", 
    blunderB: "0", 
    missedB: "0", 
    type: "blitz", 
    id: "1" }, 
    { date: "2022-11-12", 
    white: "Magnus Carlsen", 
    black: "Anish Giri", 
    winner: "1", 
    brilliantW: "9", 
    greatW: "0", 
    bestW: "0", 
    excellentW: "0", 
    goodW: "0", 
    bookW: "0", 
    inaccuracyW: "0", 
    mistakeW: "0", 
    blunderW: "0", 
    missedW: "0", 
    brilliantB: "0", 
    greatB: "0", 
    bestB: "0", 
    excellentB: "0", 
    goodB: "0", 
    bookB: "0", 
    inaccuracyB: "0", 
    mistakeB: "0", 
    blunderB: "0", 
    missedB: "0", 
    type: "rapid", 
    id: "2" }, 
    { date: "2022-08-08", 
    white: "Kevin DesLauriers", 
    black: "Magnus Carlsen", 
    winner: "1", 
    brilliantW: "9", 
    greatW: "7", 
    bestW: "6", 
    excellentW: "2", 
    goodW: "5", 
    bookW: "2", 
    inaccuracyW: "5", 
    mistakeW: "0", 
    blunderW: "0", 
    missedW: "0", 
    brilliantB: "1", 
    greatB: "1", 
    bestB: "4", 
    excellentB: "3", 
    goodB: "6", 
    bookB: "3", 
    inaccuracyB: "5", 
    mistakeB: "6", 
    blunderB: "9", 
    missedB: "8", 
    type: "classical", 
    id: "4" }] }, 

        { name: "Ding Liren", 
    id: 2, 
    classicalRating: "2811", 
    rapidRating: "2829", 
    blitzRating: "2788", 
    games: [{ date: "2022-11-01", 
    white: "Magnus Carlsen", 
    black: "Ding Liren", 
    winner: "-1", 
    brilliantW: "0", 
    greatW: "0", 
    bestW: "0", 
    excellentW: "0", 
    goodW: "0", 
    bookW: "0", 
    inaccuracyW: "0", 
    mistakeW: "0", 
    blunderW: "0", 
    missedW: "0", 
    brilliantB: "0", 
    greatB: "0", 
    bestB: "0", 
    excellentB: "0", 
    goodB: "0", 
    bookB: "0", 
    inaccuracyB: "0", 
    mistakeB: "0", 
    blunderB: "0", 
    missedB: "0", 
    type: "blitz", 
    id: "1" }] }, 

        { name: "Ian Nepomniachtchi", 
    id: 3, 
    classicalRating: "2793", 
    rapidRating: "2766", 
    blitzRating: "2781", 
    games: [{ date: "2021-04-09", 
    white: "Sergey Karjakin", 
    black: "Ian Nepomniachtchi", 
    winner: "0", 
    brilliantW: "9", 
    greatW: "8", 
    bestW: "4", 
    excellentW: "8", 
    goodW: "5", 
    bookW: "2", 
    inaccuracyW: "5", 
    mistakeW: "6", 
    blunderW: "3", 
    missedW: "1", 
    brilliantB: "9", 
    greatB: "8", 
    bestB: "2", 
    excellentB: "7", 
    goodB: "6", 
    bookB: "2", 
    inaccuracyB: "8", 
    mistakeB: "5", 
    blunderB: "3", 
    missedB: "8", 
    type: "blitz", 
    id: "8" }, 
    { date: "2023-03-03", 
    white: "Hred Fe", 
    black: "Ian Nepomniachtchi", 
    winner: "1", 
    brilliantW: "8", 
    greatW: "3", 
    bestW: "1", 
    excellentW: "6", 
    goodW: "2", 
    bookW: "4", 
    inaccuracyW: "5", 
    mistakeW: "7", 
    blunderW: "4", 
    missedW: "1", 
    brilliantB: "4", 
    greatB: "4", 
    bestB: "4", 
    excellentB: "1", 
    goodB: "5", 
    bookB: "7", 
    inaccuracyB: "2", 
    mistakeB: "1", 
    blunderB: "2", 
    missedB: "4", 
    type: "blitz", 
    id: "18" }] }, 

        { name: "Alireza Firouzja ", 
    id: 4, 
    classicalRating: "2785", 
    rapidRating: "2745", 
    blitzRating: "2903", 
    games: [] }, 

        { name: "Hikaru Nakamura", 
    id: 5, 
    classicalRating: "2768", 
    rapidRating: "2806", 
    blitzRating: "2909", 
    games: [{ date: "2021-09-18", 
    white: "Shakhiyar Mamedyarov", 
    black: "Hikaru Nakamura", 
    winner: "1", 
    brilliantW: "9", 
    greatW: "8", 
    bestW: "4", 
    excellentW: "7", 
    goodW: "3", 
    bookW: "7", 
    inaccuracyW: "3", 
    mistakeW: "1", 
    blunderW: "5", 
    missedW: "8", 
    brilliantB: "6", 
    greatB: "3", 
    bestB: "6", 
    excellentB: "9", 
    goodB: "6", 
    bookB: "4", 
    inaccuracyB: "1", 
    mistakeB: "5", 
    blunderB: "6", 
    missedB: "2", 
    type: "classical", 
    id: "7" }, 
    { date: "2021-06-23", 
    white: "Hikaru Nakamura", 
    black: "Michael Gee", 
    winner: "0", 
    brilliantW: "8", 
    greatW: "9", 
    bestW: "3", 
    excellentW: "6", 
    goodW: "21", 
    bookW: "6", 
    inaccuracyW: "2", 
    mistakeW: "7", 
    blunderW: "3", 
    missedW: "7", 
    brilliantB: "4", 
    greatB: "7", 
    bestB: "3", 
    excellentB: "2", 
    goodB: "7", 
    bookB: "8", 
    inaccuracyB: "7", 
    mistakeB: "3", 
    blunderB: "8", 
    missedB: "5", 
    type: "blitz", 
    id: "13" }] }, 

        { name: "Fabiano Caruana", 
    id: 6, 
    classicalRating: "2766", 
    rapidRating: "2747", 
    blitzRating: "2847", 
    games: [] }, 

        { name: "Anish Giri", 
    id: 7, 
    classicalRating: "2764", 
    rapidRating: "2721", 
    blitzRating: "2792", 
    games: [{ date: "2022-11-12", 
    white: "Magnus Carlsen", 
    black: "Anish Giri", 
    winner: "1", 
    brilliantW: "9", 
    greatW: "0", 
    bestW: "0", 
    excellentW: "0", 
    goodW: "0", 
    bookW: "0", 
    inaccuracyW: "0", 
    mistakeW: "0", 
    blunderW: "0", 
    missedW: "0", 
    brilliantB: "0", 
    greatB: "0", 
    bestB: "0", 
    excellentB: "0", 
    goodB: "0", 
    bookB: "0", 
    inaccuracyB: "0", 
    mistakeB: "0", 
    blunderB: "0", 
    missedB: "0", 
    type: "rapid", 
    id: "2" }, 
    { date: "2022-10-06", 
    white: "Anish Giri", 
    black: "Levon Aronian", 
    winner: "0", 
    brilliantW: "0", 
    greatW: "0", 
    bestW: "0", 
    excellentW: "0", 
    goodW: "0", 
    bookW: "0", 
    inaccuracyW: "0", 
    mistakeW: "0", 
    blunderW: "0", 
    missedW: "0", 
    brilliantB: "0", 
    greatB: "0", 
    bestB: "0", 
    excellentB: "0", 
    goodB: "0", 
    bookB: "0", 
    inaccuracyB: "0", 
    mistakeB: "0", 
    blunderB: "0", 
    missedB: "0", 
    type: "classical", 
    id: "3" }, 
    { date: "2021-06-23", 
    white: "Bill Jerman", 
    black: "Anish Giri", 
    winner: "0", 
    brilliantW: "8", 
    greatW: "9", 
    bestW: "3", 
    excellentW: "6", 
    goodW: "21", 
    bookW: "6", 
    inaccuracyW: "2", 
    mistakeW: "7", 
    blunderW: "3", 
    missedW: "7", 
    brilliantB: "4", 
    greatB: "8", 
    bestB: "65", 
    excellentB: "4", 
    goodB: "7", 
    bookB: "8", 
    inaccuracyB: "4", 
    mistakeB: "2", 
    blunderB: "8", 
    missedB: "6", 
    type: "blitz", 
    id: "14" }] }, 

        { name: "Wesley So", 
    id: 7, 
    classicalRating: "2760", 
    rapidRating: "2787", 
    blitzRating: "2763", 
    games: [{ date: "2022-11-04", 
    white: "Michael Gee", 
    black: "Wesley So", 
    winner: "0", 
    brilliantW: "9", 
    greatW: "6", 
    bestW: "5", 
    excellentW: "8", 
    goodW: "4", 
    bookW: "8", 
    inaccuracyW: "5", 
    mistakeW: "7", 
    blunderW: "4", 
    missedW: "1", 
    brilliantB: "7", 
    greatB: "3", 
    bestB: "7", 
    excellentB: "4", 
    goodB: "2", 
    bookB: "7", 
    inaccuracyB: "3", 
    mistakeB: "1", 
    blunderB: "3", 
    missedB: "1", 
    type: "rapid", 
    id: "5" }] }, 

        { name: "Viswanathan Anand", 
    id: 9, 
    classicalRating: "2754", 
    rapidRating: "2731", 
    blitzRating: "2734", 
    games: [] }, 

        { name: "Sergey Karjakin", 
    id: 10, 
    classicalRating: "2747", 
    rapidRating: "2736", 
    blitzRating: "2647", 
    games: [{ date: "2022-07-18", 
    white: "Sergey Karjakin", 
    black: "Vanessa Curran", 
    winner: "0", 
    brilliantW: "8", 
    greatW: "5", 
    bestW: "7", 
    excellentW: "2", 
    goodW: "6", 
    bookW: "9", 
    inaccuracyW: "4", 
    mistakeW: "7", 
    blunderW: "3", 
    missedW: "1", 
    brilliantB: "9", 
    greatB: "6", 
    bestB: "8", 
    excellentB: "3", 
    goodB: "1", 
    bookB: "5", 
    inaccuracyB: "8", 
    mistakeB: "5", 
    blunderB: "2", 
    missedB: "1", 
    type: "classical", 
    id: "6" }, 
    { date: "2021-04-09", 
    white: "Sergey Karjakin", 
    black: "Ian Nepomniachtchi", 
    winner: "0", 
    brilliantW: "9", 
    greatW: "8", 
    bestW: "4", 
    excellentW: "8", 
    goodW: "5", 
    bookW: "2", 
    inaccuracyW: "5", 
    mistakeW: "6", 
    blunderW: "3", 
    missedW: "1", 
    brilliantB: "9", 
    greatB: "8", 
    bestB: "2", 
    excellentB: "7", 
    goodB: "6", 
    bookB: "2", 
    inaccuracyB: "8", 
    mistakeB: "5", 
    blunderB: "3", 
    missedB: "8", 
    type: "blitz", 
    id: "8" }] }, 

        { name: "Teimour Radjabov", 
    id: 11, 
    classicalRating: "2747", 
    rapidRating: "2718", 
    blitzRating: "2709", 
    games: [] }, 

        { name: "Alexander Grischuk", 
    id: 12, 
    classicalRating: "2745", 
    rapidRating: "2759", 
    blitzRating: "2847", 
    games: [] }, 

        { name: "Leinier Dominguez Perez", 
    id: 13, 
    classicalRating: "2743", 
    rapidRating: "2703", 
    blitzRating: "2708", 
    games: [] }, 

        { name: "Shakhiyar Mamedyarov", 
    id: 14, 
    classicalRating: "2741", 
    rapidRating: "2747", 
    blitzRating: "2734", 
    games: [{ date: "2021-09-18", 
    white: "Shakhiyar Mamedyarov", 
    black: "Hikaru Nakamura", 
    winner: "1", 
    brilliantW: "9", 
    greatW: "8", 
    bestW: "4", 
    excellentW: "7", 
    goodW: "3", 
    bookW: "7", 
    inaccuracyW: "3", 
    mistakeW: "1", 
    blunderW: "5", 
    missedW: "8", 
    brilliantB: "6", 
    greatB: "3", 
    bestB: "6", 
    excellentB: "9", 
    goodB: "6", 
    bookB: "4", 
    inaccuracyB: "1", 
    mistakeB: "5", 
    blunderB: "6", 
    missedB: "2", 
    type: "classical", 
    id: "7" }] }, 

        { name: "Richard Rapport", 
    id: 15, 
    classicalRating: "2740", 
    rapidRating: "2802", 
    blitzRating: "2613", 
    games: [] }, 

        { name: "Maxime Vachier-Lagrave", 
    id: 16, 
    classicalRating: "2735", 
    rapidRating: "2775", 
    blitzRating: "2771", 
    games: [] }, 

        { name: "Levon Aronian", 
    id: 17, 
    classicalRating: "2735", 
    rapidRating: "2720", 
    blitzRating: "2809", 
    games: [{ date: "2022-10-06", 
    white: "Anish Giri", 
    black: "Levon Aronian", 
    winner: "0", 
    brilliantW: "0", 
    greatW: "0", 
    bestW: "0", 
    excellentW: "0", 
    goodW: "0", 
    bookW: "0", 
    inaccuracyW: "0", 
    mistakeW: "0", 
    blunderW: "0", 
    missedW: "0", 
    brilliantB: "0", 
    greatB: "0", 
    bestB: "0", 
    excellentB: "0", 
    goodB: "0", 
    bookB: "0", 
    inaccuracyB: "0", 
    mistakeB: "0", 
    blunderB: "0", 
    missedB: "0", 
    type: "classical", 
    id: "3" }, 
    { date: "2021-06-23", 
    white: "Levon Aronian", 
    black: "Peddy Torfiris", 
    winner: "-1", 
    brilliantW: "8", 
    greatW: "9", 
    bestW: "3", 
    excellentW: "6", 
    goodW: "21", 
    bookW: "6", 
    inaccuracyW: "2", 
    mistakeW: "7", 
    blunderW: "3", 
    missedW: "7", 
    brilliantB: "4", 
    greatB: "7", 
    bestB: "3", 
    excellentB: "2", 
    goodB: "7", 
    bookB: "8", 
    inaccuracyB: "7", 
    mistakeB: "3", 
    blunderB: "8", 
    missedB: "5", 
    type: "rapid", 
    id: "12" }] }, 

        { name: "Jan-Krzysztof Duda", 
    id: 18, 
    classicalRating: "2731", 
    rapidRating: "2791", 
    blitzRating: "2779", 
    games: [{ date: "2023-03-03", 
    white: "Jan-Krzysztof Duda", 
    black: "Alan Gao", 
    winner: "1", 
    brilliantW: "8", 
    greatW: "3", 
    bestW: "1", 
    excellentW: "6", 
    goodW: "2", 
    bookW: "4", 
    inaccuracyW: "5", 
    mistakeW: "7", 
    blunderW: "4", 
    missedW: "1", 
    brilliantB: "4", 
    greatB: "4", 
    bestB: "4", 
    excellentB: "1", 
    goodB: "5", 
    bookB: "7", 
    inaccuracyB: "2", 
    mistakeB: "1", 
    blunderB: "2", 
    missedB: "4", 
    type: "classical", 
    id: "17" }] }, 

        { name: "Vidit Santosh Gujrathi", 
    id: 19, 
    classicalRating: "2729", 
    rapidRating: "2617", 
    blitzRating: "2654", 
    games: [] }, 

        { name: "Dmitry Andreikin", 
    id: 20, 
    classicalRating: "2729", 
    rapidRating: "2634", 
    blitzRating: "2736", 
    games: [] }, 

        { name: "Kevin DesLauriers", 
    id: "21", 
    classicalRating: "4872", 
    rapidRating: "9182", 
    blitzRating: "6712", 
    games: [{ date: "2022-08-08", 
    white: "Kevin DesLauriers", 
    black: "Magnus Carlsen", 
    winner: "1", 
    brilliantW: "9", 
    greatW: "7", 
    bestW: "6", 
    excellentW: "2", 
    goodW: "5", 
    bookW: "2", 
    inaccuracyW: "5", 
    mistakeW: "0", 
    blunderW: "0", 
    missedW: "0", 
    brilliantB: "1", 
    greatB: "1", 
    bestB: "4", 
    excellentB: "3", 
    goodB: "6", 
    bookB: "3", 
    inaccuracyB: "5", 
    mistakeB: "6", 
    blunderB: "9", 
    missedB: "8", 
    type: "classical", 
    id: "4" }] }, 

        { name: "Nathan Baroni", 
    id: "22", 
    classicalRating: "8", 
    rapidRating: "2000", 
    blitzRating: "69420", 
    games: [] }, 

        { name: "Vanessa Curran", 
    id: "23", 
    classicalRating: "5916", 
    rapidRating: "9947", 
    blitzRating: "93712", 
    games: [{ date: "2022-07-18", 
    white: "Sergey Karjakin", 
    black: "Vanessa Curran", 
    winner: "0", 
    brilliantW: "8", 
    greatW: "5", 
    bestW: "7", 
    excellentW: "2", 
    goodW: "6", 
    bookW: "9", 
    inaccuracyW: "4", 
    mistakeW: "7", 
    blunderW: "3", 
    missedW: "1", 
    brilliantB: "9", 
    greatB: "6", 
    bestB: "8", 
    excellentB: "3", 
    goodB: "1", 
    bookB: "5", 
    inaccuracyB: "8", 
    mistakeB: "5", 
    blunderB: "2", 
    missedB: "1", 
    type: "classical", 
    id: "6" }] }, 

        { name: "Michael Gee", 
    id: "24", 
    classicalRating: "2760", 
    rapidRating: "2536", 
    blitzRating: "1987", 
    games: [{ date: "2022-11-04", 
    white: "Michael Gee", 
    black: "Wesley So", 
    winner: "0", 
    brilliantW: "9", 
    greatW: "6", 
    bestW: "5", 
    excellentW: "8", 
    goodW: "4", 
    bookW: "8", 
    inaccuracyW: "5", 
    mistakeW: "7", 
    blunderW: "4", 
    missedW: "1", 
    brilliantB: "7", 
    greatB: "3", 
    bestB: "7", 
    excellentB: "4", 
    goodB: "2", 
    bookB: "7", 
    inaccuracyB: "3", 
    mistakeB: "1", 
    blunderB: "3", 
    missedB: "1", 
    type: "rapid", 
    id: "5" }, 
    { date: "2022-11-19", 
    white: "Michael Gee", 
    black: "Derek Law", 
    winner: "-1", 
    brilliantW: "3", 
    greatW: "9", 
    bestW: "6", 
    excellentW: "8", 
    goodW: "4", 
    bookW: "7", 
    inaccuracyW: "2", 
    mistakeW: "7", 
    blunderW: "2", 
    missedW: "6", 
    brilliantB: "0", 
    greatB: "8", 
    bestB: "9", 
    excellentB: "3", 
    goodB: "7", 
    bookB: "2", 
    inaccuracyB: "7", 
    mistakeB: "1", 
    blunderB: "2", 
    missedB: "1", 
    type: "rapid", 
    id: "9" }, 
    { date: "2021-06-23", 
    white: "Hikaru Nakamura", 
    black: "Michael Gee", 
    winner: "0", 
    brilliantW: "8", 
    greatW: "9", 
    bestW: "3", 
    excellentW: "6", 
    goodW: "21", 
    bookW: "6", 
    inaccuracyW: "2", 
    mistakeW: "7", 
    blunderW: "3", 
    missedW: "7", 
    brilliantB: "4", 
    greatB: "7", 
    bestB: "3", 
    excellentB: "2", 
    goodB: "7", 
    bookB: "8", 
    inaccuracyB: "7", 
    mistakeB: "3", 
    blunderB: "8", 
    missedB: "5", 
    type: "blitz", 
    id: "13" }] }, 

        { name: "Derek Law", 
    id: "25", 
    classicalRating: "3079", 
    rapidRating: "3086", 
    blitzRating: "3125", 
    games: [{ date: "2022-11-19", 
    white: "Michael Gee", 
    black: "Derek Law", 
    winner: "-1", 
    brilliantW: "3", 
    greatW: "9", 
    bestW: "6", 
    excellentW: "8", 
    goodW: "4", 
    bookW: "7", 
    inaccuracyW: "2", 
    mistakeW: "7", 
    blunderW: "2", 
    missedW: "6", 
    brilliantB: "0", 
    greatB: "8", 
    bestB: "9", 
    excellentB: "3", 
    goodB: "7", 
    bookB: "2", 
    inaccuracyB: "7", 
    mistakeB: "1", 
    blunderB: "2", 
    missedB: "1", 
    type: "rapid", 
    id: "9" }] }, 

        { name: "Lauryn Chau", 
    id: "26", 
    classicalRating: "10", 
    rapidRating: "10", 
    blitzRating: "10", 
    games: [] }, 

        { name: "Samantha Sedran", 
    id: "27", 
    classicalRating: "45", 
    rapidRating: "52", 
    blitzRating: "17", 
    games: [] }, 

        { name: "Diego Islas", 
    id: "28", 
    classicalRating: "2873", 
    rapidRating: "2983", 
    blitzRating: "2319", 
    games: [{ date: "2023-03-03", 
    white: "Iucas Lskander", 
    black: "Diego Islas", 
    winner: "1", 
    brilliantW: "8", 
    greatW: "3", 
    bestW: "1", 
    excellentW: "6", 
    goodW: "2", 
    bookW: "4", 
    inaccuracyW: "5", 
    mistakeW: "7", 
    blunderW: "4", 
    missedW: "1", 
    brilliantB: "4", 
    greatB: "4", 
    bestB: "4", 
    excellentB: "1", 
    goodB: "5", 
    bookB: "7", 
    inaccuracyB: "2", 
    mistakeB: "1", 
    blunderB: "2", 
    missedB: "4", 
    type: "classical", 
    id: "16" }] }, 

        { name: "Brant Gourne", 
    id: "29", 
    classicalRating: "3928", 
    rapidRating: "3769", 
    blitzRating: "2379", 
    games: [{ date: "2021-06-23", 
    white: "Brant Gourne", 
    black: "Devin KesLauriers", 
    winner: "0", 
    brilliantW: "8", 
    greatW: "9", 
    bestW: "3", 
    excellentW: "6", 
    goodW: "21", 
    bookW: "6", 
    inaccuracyW: "2", 
    mistakeW: "7", 
    blunderW: "3", 
    missedW: "7", 
    brilliantB: "4", 
    greatB: "7", 
    bestB: "3", 
    excellentB: "2", 
    goodB: "7", 
    bookB: "8", 
    inaccuracyB: "7", 
    mistakeB: "3", 
    blunderB: "8", 
    missedB: "5", 
    type: "classical", 
    id: "11" }] }, 

        { name: "Mristan Terkley", 
    id: "30", 
    classicalRating: "4273", 
    rapidRating: "2837", 
    blitzRating: "2386", 
    games: [] }, 

        { name: "Hara Sobson", 
    id: "31", 
    classicalRating: "1726", 
    rapidRating: "8724", 
    blitzRating: "2875", 
    games: [] }, 

        { name: "Iucas Lskander", 
    id: "32", 
    classicalRating: "4876", 
    rapidRating: "2387", 
    blitzRating: "4768", 
    games: [{ date: "2023-03-03", 
    white: "Iucas Lskander", 
    black: "Diego Islas", 
    winner: "1", 
    brilliantW: "8", 
    greatW: "3", 
    bestW: "1", 
    excellentW: "6", 
    goodW: "2", 
    bookW: "4", 
    inaccuracyW: "5", 
    mistakeW: "7", 
    blunderW: "4", 
    missedW: "1", 
    brilliantB: "4", 
    greatB: "4", 
    bestB: "4", 
    excellentB: "1", 
    goodB: "5", 
    bookB: "7", 
    inaccuracyB: "2", 
    mistakeB: "1", 
    blunderB: "2", 
    missedB: "4", 
    type: "classical", 
    id: "16" }] }, 

        { name: "Peddy Torfiris", 
    id: "33", 
    classicalRating: "2375", 
    rapidRating: "3847", 
    blitzRating: "2365", 
    games: [{ date: "2021-06-23", 
    white: "Levon Aronian", 
    black: "Peddy Torfiris", 
    winner: "-1", 
    brilliantW: "8", 
    greatW: "9", 
    bestW: "3", 
    excellentW: "6", 
    goodW: "21", 
    bookW: "6", 
    inaccuracyW: "2", 
    mistakeW: "7", 
    blunderW: "3", 
    missedW: "7", 
    brilliantB: "4", 
    greatB: "7", 
    bestB: "3", 
    excellentB: "2", 
    goodB: "7", 
    bookB: "8", 
    inaccuracyB: "7", 
    mistakeB: "3", 
    blunderB: "8", 
    missedB: "5", 
    type: "rapid", 
    id: "12" }] }, 

        { name: "Yshley Aeung", 
    id: "34", 
    classicalRating: "1876", 
    rapidRating: "654", 
    blitzRating: "1756", 
    games: [] }, 

        { name: "Batie Khalla", 
    id: "35", 
    classicalRating: "2398", 
    rapidRating: "2938", 
    blitzRating: "3478", 
    games: [] }, 

        { name: "Faya Mreedman", 
    id: "36", 
    classicalRating: "1876", 
    rapidRating: "980", 
    blitzRating: "764", 
    games: [] }, 

        { name: "Sames Jimmons", 
    id: "38", 
    classicalRating: "1838", 
    rapidRating: "1822", 
    blitzRating: "654", 
    games: [] }, 

        { name: "Grant Bourne", 
    id: "39", 
    classicalRating: "2398", 
    rapidRating: "9238", 
    blitzRating: "2398", 
    games: [] }, 

        { name: "Etefano Ssposto", 
    id: "40", 
    classicalRating: "2387", 
    rapidRating: "2356", 
    blitzRating: "1276", 
    games: [] }, 

        { name: "Hred Fe", 
    id: "41", 
    classicalRating: "2387", 
    rapidRating: "2387", 
    blitzRating: "2389", 
    games: [{ date: "2023-03-03", 
    white: "Hred Fe", 
    black: "Ian Nepomniachtchi", 
    winner: "1", 
    brilliantW: "8", 
    greatW: "3", 
    bestW: "1", 
    excellentW: "6", 
    goodW: "2", 
    bookW: "4", 
    inaccuracyW: "5", 
    mistakeW: "7", 
    blunderW: "4", 
    missedW: "1", 
    brilliantB: "4", 
    greatB: "4", 
    bestB: "4", 
    excellentB: "1", 
    goodB: "5", 
    bookB: "7", 
    inaccuracyB: "2", 
    mistakeB: "1", 
    blunderB: "2", 
    missedB: "4", 
    type: "blitz", 
    id: "18" }, 
    { date: "2022-11-25", 
    white: "Alan Gao", 
    black: "Hred Fe", 
    winner: "0", 
    brilliantW: "0", 
    greatW: "0", 
    bestW: "0", 
    excellentW: "0", 
    goodW: "0", 
    bookW: "0", 
    inaccuracyW: "0", 
    mistakeW: "0", 
    blunderW: "0", 
    missedW: "0", 
    brilliantB: "0", 
    greatB: "0", 
    bestB: "0", 
    excellentB: "0", 
    goodB: "0", 
    bookB: "0", 
    inaccuracyB: "0", 
    mistakeB: "0", 
    blunderB: "0", 
    missedB: "0", 
    type: "rapid", 
    id: "19" }] }, 

        { name: "Pavid Derry", 
    id: "42", 
    classicalRating: "4876", 
    rapidRating: "2354", 
    blitzRating: "723", 
    games: [] }, 

        { name: "Devin KesLauriers", 
    id: "43", 
    classicalRating: "765", 
    rapidRating: "423", 
    blitzRating: "654", 
    games: [{ date: "2021-06-23", 
    white: "Brant Gourne", 
    black: "Devin KesLauriers", 
    winner: "0", 
    brilliantW: "8", 
    greatW: "9", 
    bestW: "3", 
    excellentW: "6", 
    goodW: "21", 
    bookW: "6", 
    inaccuracyW: "2", 
    mistakeW: "7", 
    blunderW: "3", 
    missedW: "7", 
    brilliantB: "4", 
    greatB: "7", 
    bestB: "3", 
    excellentB: "2", 
    goodB: "7", 
    bookB: "8", 
    inaccuracyB: "7", 
    mistakeB: "3", 
    blunderB: "8", 
    missedB: "5", 
    type: "classical", 
    id: "11" }] }, 

        { name: "Jebediah Kerman", 
    id: "44", 
    classicalRating: "586", 
    rapidRating: "789", 
    blitzRating: "678", 
    games: [{ date: "2021-06-23", 
    white: "Jebediah Kerman", 
    black: "Weep Woop", 
    winner: "1", 
    brilliantW: "8", 
    greatW: "9", 
    bestW: "3", 
    excellentW: "6", 
    goodW: "21", 
    bookW: "6", 
    inaccuracyW: "2", 
    mistakeW: "7", 
    blunderW: "3", 
    missedW: "7", 
    brilliantB: "4", 
    greatB: "7", 
    bestB: "3", 
    excellentB: "2", 
    goodB: "7", 
    bookB: "8", 
    inaccuracyB: "7", 
    mistakeB: "3", 
    blunderB: "8", 
    missedB: "5", 
    type: "blitz", 
    id: "10" }] }, 

        { name: "Kob Berman", 
    id: "45", 
    classicalRating: "2376", 
    rapidRating: "857", 
    blitzRating: "980", 
    games: [] }, 

        { name: "Bob Kerman", 
    id: "46", 
    classicalRating: "2376", 
    rapidRating: "823", 
    blitzRating: "2876", 
    games: [] }, 

        { name: "Valentina Kerman", 
    id: "47", 
    classicalRating: "2397", 
    rapidRating: "879", 
    blitzRating: "653", 
    games: [{ date: "2023-03-03", 
    white: "Valentina Kerman", 
    black: "Geller Wao", 
    winner: "-1", 
    brilliantW: "8", 
    greatW: "3", 
    bestW: "1", 
    excellentW: "6", 
    goodW: "2", 
    bookW: "4", 
    inaccuracyW: "5", 
    mistakeW: "7", 
    blunderW: "4", 
    missedW: "1", 
    brilliantB: "4", 
    greatB: "4", 
    bestB: "4", 
    excellentB: "1", 
    goodB: "5", 
    bookB: "7", 
    inaccuracyB: "2", 
    mistakeB: "1", 
    blunderB: "2", 
    missedB: "4", 
    type: "rapid", 
    id: "15" }] }, 

        { name: "Bill Kerman", 
    id: "48", 
    classicalRating: "2300", 
    rapidRating: "917", 
    blitzRating: "391", 
    games: [] }, 

        { name: "Geller Wao", 
    id: "49", 
    classicalRating: "2197", 
    rapidRating: "3019", 
    blitzRating: "2007", 
    games: [{ date: "2023-03-03", 
    white: "Valentina Kerman", 
    black: "Geller Wao", 
    winner: "-1", 
    brilliantW: "8", 
    greatW: "3", 
    bestW: "1", 
    excellentW: "6", 
    goodW: "2", 
    bookW: "4", 
    inaccuracyW: "5", 
    mistakeW: "7", 
    blunderW: "4", 
    missedW: "1", 
    brilliantB: "4", 
    greatB: "4", 
    bestB: "4", 
    excellentB: "1", 
    goodB: "5", 
    bookB: "7", 
    inaccuracyB: "2", 
    mistakeB: "1", 
    blunderB: "2", 
    missedB: "4", 
    type: "rapid", 
    id: "15" }] }, 

        { name: "Bill Jerman", 
    id: "50", 
    classicalRating: "2399", 
    rapidRating: "2376", 
    blitzRating: "1267", 
    games: [{ date: "2021-06-23", 
    white: "Bill Jerman", 
    black: "Anish Giri", 
    winner: "0", 
    brilliantW: "8", 
    greatW: "9", 
    bestW: "3", 
    excellentW: "6", 
    goodW: "21", 
    bookW: "6", 
    inaccuracyW: "2", 
    mistakeW: "7", 
    blunderW: "3", 
    missedW: "7", 
    brilliantB: "4", 
    greatB: "8", 
    bestB: "65", 
    excellentB: "4", 
    goodB: "7", 
    bookB: "8", 
    inaccuracyB: "4", 
    mistakeB: "2", 
    blunderB: "8", 
    missedB: "6", 
    type: "blitz", 
    id: "14" }] }, 

        { name: "Alan Gao", 
    id: "51", 
    classicalRating: "800", 
    rapidRating: "209", 
    blitzRating: "3019", 
    games: [{ date: "2023-03-03", 
    white: "Jan-Krzysztof Duda", 
    black: "Alan Gao", 
    winner: "1", 
    brilliantW: "8", 
    greatW: "3", 
    bestW: "1", 
    excellentW: "6", 
    goodW: "2", 
    bookW: "4", 
    inaccuracyW: "5", 
    mistakeW: "7", 
    blunderW: "4", 
    missedW: "1", 
    brilliantB: "4", 
    greatB: "4", 
    bestB: "4", 
    excellentB: "1", 
    goodB: "5", 
    bookB: "7", 
    inaccuracyB: "2", 
    mistakeB: "1", 
    blunderB: "2", 
    missedB: "4", 
    type: "classical", 
    id: "17" }, 
    { date: "2022-11-25", 
    white: "Alan Gao", 
    black: "Hred Fe", 
    winner: "0", 
    brilliantW: "0", 
    greatW: "0", 
    bestW: "0", 
    excellentW: "0", 
    goodW: "0", 
    bookW: "0", 
    inaccuracyW: "0", 
    mistakeW: "0", 
    blunderW: "0", 
    missedW: "0", 
    brilliantB: "0", 
    greatB: "0", 
    bestB: "0", 
    excellentB: "0", 
    goodB: "0", 
    bookB: "0", 
    inaccuracyB: "0", 
    mistakeB: "0", 
    blunderB: "0", 
    missedB: "0", 
    type: "rapid", 
    id: "19" }] }, 

        { name: "Weep Woop", 
    id: "52", 
    classicalRating: "328", 
    rapidRating: "283", 
    blitzRating: "289", 
    games: [{ date: "2021-06-23", 
    white: "Jebediah Kerman", 
    black: "Weep Woop", 
    winner: "1", 
    brilliantW: "8", 
    greatW: "9", 
    bestW: "3", 
    excellentW: "6", 
    goodW: "21", 
    bookW: "6", 
    inaccuracyW: "2", 
    mistakeW: "7", 
    blunderW: "3", 
    missedW: "7", 
    brilliantB: "4", 
    greatB: "7", 
    bestB: "3", 
    excellentB: "2", 
    goodB: "7", 
    bookB: "8", 
    inaccuracyB: "7", 
    mistakeB: "3", 
    blunderB: "8", 
    missedB: "5", 
    type: "blitz", 
    id: "10" }] }, 

        { name: "Handra Paki", 
    id: "53", 
    classicalRating: "2387", 
    rapidRating: "7828", 
    blitzRating: "1276", 
    games: [] }, 

        { name: "Gichael Mee", 
    id: "54", 
    "classicalRating": "1928", 
    rapidRating: "2916", 
    blitzRating: "9816", 
    games: [] }
];



let playersString = JSON.stringify(players);
// let data = localStorage.setItem("data", playersString)
let data = JSON.parse(localStorage.getItem("data"))

if (localStorage.getItem("data") != playersString) {
    data = JSON.parse(localStorage.getItem("data"))
} else {
    localStorage.setItem("data", playersString);
    data = JSON.parse(localStorage.getItem("data"));
}

let seenID = ["0"]
let seenString = JSON.stringify(seenID);
let seen = JSON.parse(localStorage.getItem("seen"))

if (localStorage.getItem("seen") != seenString) {
    seen = JSON.parse(localStorage.getItem("seen"))
} else {
    localStorage.setItem("seen", seenString);
    seen = JSON.parse(localStorage.getItem("seen"));
}

console.log(JSON.stringify(data))

let rankSort = "descending"
let classicalSort = "descending"
let rapidSort = "descending"
let blitzSort = "descending"
let nameSort = "descending"

let page = 10;

let leftButton = document.getElementById("oneBefore")
let centerButton = document.getElementById("current")
let rightButton = document.getElementById("oneAfter")
let lastButton = document.getElementById("lastButton")

fillPaginationButtons(page)
sort('rank', rankSort)

function fillPaginationButtons(page) {
    let leftDot = document.getElementById("leftDot")
    let rightDot = document.getElementById("rightDot")
    let outOf = document.getElementById("outOf")
    let max = data.length - data.length % 10
    max += 10
    max /= 10
    num = page / 10;
    lastButton.textContent = max
    lastButton.setAttribute("onclick", "setPaginate('last')")
    if (num == 1) {
        leftButton.textContent = 2
        centerButton.textContent = 3
        rightButton.textContent = 4
        leftButton.setAttribute("onclick", "setPaginate('left')")
        centerButton.setAttribute("onclick", "setPaginate('center')")
        rightButton.setAttribute("onclick", "setPaginate('right')")
        rightButton.classList.remove("is-hidden")
        outOf.textContent = "(" + num.toString() + " of " + max.toString() + ")"
    }
    else if (num === 2) {
        leftButton.textContent = 2
        centerButton.textContent = 3
        rightButton.textContent = 4
        leftButton.setAttribute("onclick", "setPaginate('left')")
        centerButton.setAttribute("onclick", "setPaginate('center')")
        rightButton.setAttribute("onclick", "setPaginate('right')")
        rightButton.classList.remove("is-hidden")
        outOf.textContent = "(" + num.toString() + " of " + max.toString() + ")"
    } else if (num >= 3 && page < data.length && num < max - 1) {
        leftButton.textContent = num - 1
        centerButton.textContent = num
        rightButton.textContent = num + 1
        leftButton.setAttribute("onclick", "setPaginate('left')")
        centerButton.setAttribute("onclick", "setPaginate('center')")
        rightButton.setAttribute("onclick", "setPaginate('right')")
        rightButton.classList.remove("is-hidden")
        outOf.textContent = "(" + num.toString() + " of " + max.toString() + ")"
    } else if (num >= max - 1) {
        leftButton.setAttribute("onclick", "setPaginate('left')")
        centerButton.setAttribute("onclick", "setPaginate('center')")
        rightButton.setAttribute("onclick", "setPaginate('right')")
        outOf.textContent = "(" + num.toString() + " of " + max.toString() + ")"
    }
}

function paginate(num) {
    page += num
    if (page < 10) {
        page = 10;
    } else if (page > data.length) {
        page = data.length
        page = page - page % 10
        page += 10
    }
    createTable(data)
    fillPaginationButtons(page)
}

function setPaginate(prop) {
    if (prop === "10") {
        page = 10
        createTable(data)
        fillPaginationButtons(page)
    } else if (prop === "left") {
        page = parseInt(leftButton.textContent) * 10
        createTable(data)
        fillPaginationButtons(page)
    } else if (prop === "center") {
        page = parseInt(centerButton.textContent) * 10
        createTable(data)
        fillPaginationButtons(page)
    } else if (prop === "right") {
        page = parseInt(rightButton.textContent) * 10
        createTable(data)
        fillPaginationButtons(page)
    } else if (prop === "last") {
        page = parseInt(lastButton.textContent) * 10
        createTable(data)
        fillPaginationButtons(page)
    }
}

function createTable(data) {
    let tableBody = document.querySelector('tbody');
    tableBody.replaceChildren();
    for (let j = page - 10; j < page; j++) {
        if (data[j] != null) {
            const row = document.createElement('tr');
            let cell = document.createElement('td');
            let link = document.createElement('a');
            cellRank = document.createElement('td');
            cellRank.textContent = j + 1;
            row.appendChild(cellRank);

            cell = document.createElement('td');
            link.href = 'players.html?id=' + data[j].id;
            link.textContent = data[j].name;
            cell.appendChild(link);
            row.appendChild(cell);
            cell = document.createElement('td');
            cell.textContent = data[j].classicalRating;
            row.appendChild(cell);
            cell = document.createElement('td');
            cell.textContent = data[j].rapidRating;
            row.appendChild(cell);
            cell = document.createElement('td');
            cell.textContent = data[j].blitzRating;
            row.appendChild(cell);
            tableBody.appendChild(row);
        }
    }
}

function sort(prop, sort) {
    let iconRank = document.getElementById("rank")
    let iconName = document.getElementById("name")
    let iconClass = document.getElementById("class")
    let iconRapid = document.getElementById("rapid")
    let iconBlitz = document.getElementById("blitz")
    iconRank.setAttribute('class', "")
    iconName.setAttribute('class', "")
    iconClass.setAttribute('class', "")
    iconRapid.setAttribute('class', "")
    iconBlitz.setAttribute('class', "")

    let tableBody = document.querySelector('tbody');
    let rankFlag = false
    if (prop === "rank") {
        prop = "classicalRating"
        rankFlag = true
    }
    tableBody.replaceChildren();
    let store = "";
    if (sort === "descending") {
        for (let j = 0; j < data.length + 5; j++) {
            for (let i = 0; i < data.length - 1; i++) {
                let currentElement = data[i];
                let nextElement = data[i + 1];
                if (prop === 'name') {
                    iconName.setAttribute('class', "fa-solid fa-chevron-down")
                    if (currentElement[prop] > nextElement[prop]) {
                        store = currentElement;
                        data[i] = data[i + 1];
                        data[i + 1] = store;
                    }
                    nameSort = "ascending"
                } else if (parseInt(currentElement[prop]) < parseInt(nextElement[prop])) {
                    store = currentElement;
                    data[i] = data[i + 1];
                    data[i + 1] = store;
                }
            }
        }
        if (prop === "classicalRating" && !rankFlag) {
            iconClass.setAttribute('class', "fa-solid fa-chevron-down")
            classicalSort = "ascending"
        } else if (prop === "rapidRating" && !rankFlag) {
            iconRapid.setAttribute('class', "fa-solid fa-chevron-down")
            rapidSort = "ascending"
        } else if (prop === "blitzRating" && !rankFlag) {
            iconBlitz.setAttribute('class', "fa-solid fa-chevron-down")
            blitzSort = "ascending"
        } else if (prop === "classicalRating" && rankFlag) {
            iconRank.setAttribute('class', "fa-solid fa-chevron-down")
            rankSort = "ascending"
        }
    } else if (sort === "ascending") {
        for (let j = 0; j < data.length + 5; j++) {
            for (let i = 0; i < data.length - 1; i++) {
                let currentElement = data[i]
                let nextElement = data[i + 1];
                if (prop === 'name') {
                    iconName.setAttribute('class', "fa-solid fa-chevron-up")
                    if (currentElement[prop] < nextElement[prop]) {
                        store = currentElement;
                        data[i] = data[i + 1];
                        data[i + 1] = store;
                    }
                    nameSort = "descending"
                } else if (parseInt(currentElement[prop]) > parseInt(nextElement[prop])) {
                    store = currentElement;
                    data[i] = data[i + 1];
                    data[i + 1] = store;
                }
            }
        }
        if (prop === "classicalRating" && !rankFlag) {
            iconClass.setAttribute('class', "fa-solid fa-chevron-up")
            classicalSort = "descending"
        } else if (prop === "rapidRating" && !rankFlag) {
            iconRapid.setAttribute('class', "fa-solid fa-chevron-up")
            rapidSort = "descending"
        } else if (prop === "blitzRating" && !rankFlag) {
            iconBlitz.setAttribute('class', "fa-solid fa-chevron-up")
            blitzSort = "descending"
        } else if (prop === "classicalRating" && rankFlag) {
            iconRank.setAttribute('class', "fa-solid fa-chevron-up")
            rankSort = "descending"
        }
    }
    createTable(data);
}